---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator-subscription
  namespace: openshift-operators
spec:
  channel: "4.5"
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
